---

- name: copy assetfinder shell script into {{ target }} directory
  template:
    src: templates/assetfinder.j2
    dest: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}/assetfinder.sh
    owner: '{{user_name }}'
    group: '{{user_name }}'
    mode: '0755'

- name: run assetfinder shell script for subdomain eumeration on {{ target }}
  become: yes
  become_user: "{{ user_name }}"
  shell: ./assetfinder.sh  
  args:
    chdir: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}