---

- name: create directory for "{{ target }}"
  become: yes
  become_user: "{{ user_name }}"
  file:
    path: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}
    state: directory
  tags: directory