---

- name: use httprobe on {{ target }}-hosts-online
  shell: cat *hosts-online.txt | httprobe > {{ target | quote }}-{{ ansible_date_time.date | quote }}-httprobe output
  args: 
    chdir: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}
  register: shell_output
  tags: httprobe 
  
- debug: msg={{ shell_output.stdout }}