---

- name: scan "{{ target }}" with findomain
  shell: findomain -t {{ target | quote }} -u SUB-findomain-output-{{ target | quote }}-{{ ansible_date_time.date | quote }}.txt
  async: 2592000               # 60*60*24*30 â€“ 1 month
  poll: 0
  args: 
    chdir: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}/



