---

- name: Copy nmap bash script to "{{ target }}" directory
  template:
    src: nmap-convert.j2
    dest: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}/nmap-convert.sh
    force: yes
    owner: root
    group: root
    mode: 0755
  tags: nmap

- name: execute nmap-convert.sh on {{ target }}   
  become: yes
  shell: ./nmap-convert.sh
  args:
    chdir: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}
  register: shell_output
  tags: execute 

- debug: msg={{ shell_output.stdout }}