---

- name: scan "{{ target }}" with masscan from  ip addresses obtained from {{ target }}-{{ ansible_date_time.date }}-ips-online.txt
  shell: masscan -iL {{ target | quote }}-{{ ansible_date_time.date | quote }}-ips-online.txt --rate 10000 -p1-65535 --open -oJ {{ target | quote }}-{{ ansible_date_time.date | quote }}-list-masscan-results 
  args: 
    chdir: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}
  register: shell_output
  tags: masscan  

- debug: msg={{ shell_output.stdout }}