---

- name: copy Hakcrawler shell script into {{ target }} directory
  template:
    src: templates/Hakcrawler.j2
    dest: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}/Hakcrawler.sh
    owner: '{{user_name }}'
    group: '{{user_name }}'
    mode: '0755'
  
- name: run Hakcrawler shell script on {{ target }}
  become: yes
  become_user: "{{ user_name }}"
  shell: ./Hakcrawler.sh 
  register: Hakcrawler
  args:
    chdir: /home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }}
  
- debug: 
    msg: '{{ Hakcrawler.stdout }}'
  



