---

- name: execute scp on local machine to retrieve files
  local_action: shell scp -r -P 2277 {{ user_name }}@{{ remote_ip }}:/home/{{ user_name }}/massdns/{{ target }}-{{ ansible_date_time.date }} {{ playbook_dir }}
  tags: scp 
 